<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class StudyProgramSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $programs = [
            [
                'study_program_Name' => 'PENDIDIKAN DOKTER - S1',
                'ID_Faculty' => 3,
                'study_program_Image' => $this->storeImage('FK-unhas.png'),
                'study_program_Description' =>'',
                'degree' => 'Undergraduate',
                'classrooms' => 0,
                'lecturers' => 0,
                'national_accreditation' => '',
                'international_accreditation' => '',
                'approval_sk' => null,
                'opening_year' => null,
                'director_name' => null,
                'director_contact' => null,
                'ukt_fee' => null,
                'ipi_fee' => null,
                'international_exposure' => null,
                'total_courses' => 56,
                'rps_courses_in_english' => 10,
                'teaching_materials_in_english' => 0,
                'courses_delivered_in_english' => 0,
                'courses_fully_filled_in_sikola' => 0, 
            ],
            [
                'study_program_Name' => 'PENDIDIKAN DOKTER GIGI - S1',
                'ID_Faculty' => 10,
                'study_program_Image' => $this->storeImage('doktergigi.png'),
                'study_program_Description' =>'The International Class Program of the Faculty of Dentistry has been established since 2019. The International Class Program is a professional education program aimed at applying knowledge in the field of dentistry, encompassing general sciences, basic and clinical medical and dental sciences, as well as community dental health, to produce professional and competent dentists. The number of students enrolled in the International Class is 129. The International Class at the Faculty of Dentistry, Hasanuddin University, has dedicated classrooms separate from the regular classes. The learning process is conducted in English, including teaching methods and learning media such as PowerPoint presentations and teaching modules. Each academic block features one foreign lecturer who teaches either online or in person.',
                'degree' => 'Undergraduate',
                'classrooms' => 4,
                'lecturers' => 90,
                'national_accreditation' => 'Unggul',
                'international_accreditation' => 'ASIIN',
                'approval_sk' => 'SK Kelas Internasional No. 419/UN4.13/KEP/2019',
                'opening_year' => 2019,
                'director_name' => 'drg. Andi Sri Permatasari, Sp.KGA',
                'director_contact' => '082195006161',
                'ukt_fee' => 22500000,
                'ipi_fee' => 225000000,
                'international_exposure' => 'Sit In, Summer Course, Student Exchange, Enrichment Program',
                'total_courses' => 23,
                'rps_courses_in_english' => 20,
                'teaching_materials_in_english' => 20,
                'courses_delivered_in_english' => 23,
                'courses_fully_filled_in_sikola' => 5, 
            ],
            [
                'study_program_Name' => 'ILMU KEPERAWATAN - S1',
                'ID_Faculty' => 15,
                'study_program_Image' => $this->storeImage('keperawatan.png'),
                'study_program_Description' =>'',
                'degree' => 'Undergraduate',
                'classrooms' => 0,
                'lecturers' => 0,
                'national_accreditation' => '',
                'international_accreditation' => '',
                'approval_sk' => null,
                'opening_year' => null,
                'director_name' => 'Andi Baso Tombong, S.Kep.Ns.M.ANP',
                'director_contact' => '08114450480',
                'ukt_fee' => null,
                'ipi_fee' => null,
                'international_exposure' => null,
                'total_courses' => 0,
                'rps_courses_in_english' => 0,
                'teaching_materials_in_english' => 0,
                'courses_delivered_in_english' => 0,
                'courses_fully_filled_in_sikola' => 0, 
            ],
            [
                'study_program_Name' => 'KESEHATAN MASYARAKAT - S1',
                'ID_Faculty' => 11,
                'study_program_Image' => $this->storeImage('kesmas.png'),
                'study_program_Description' =>'The International Class Program of the Faculty of Public Health, Hasanuddin University, has been established since 2016 and has graduated a total of 5 alumni.',
                'degree' => 'Undergraduate',
                'classrooms' => 0,
                'lecturers' => 0,
                'national_accreditation' => 'Unggul',
                'international_accreditation' => 'ASIIN',
                'approval_sk' => null,
                'opening_year' => 2016,
                'director_name' => 'Dr. Hasnawati Amqam, SKM.,M.Sc',
                'director_contact' => '08114630476',
                'ukt_fee' => null,
                'ipi_fee' => null,
                'international_exposure' => 'Conference, Sit In',
                'total_courses' => 119,
                'rps_courses_in_english' => 2,
                'teaching_materials_in_english' => 2,
                'courses_delivered_in_english' => 0,
                'courses_fully_filled_in_sikola' => 0, 
            ],
            [
                'study_program_Name' => 'TEKNIK SIPIL - S1',
                'ID_Faculty' => 4,
                'study_program_Image' => $this->storeImage('sipil.png'),
                'study_program_Description' =>'',
                'degree' => 'Undergraduate',
                'classrooms' => 0,
                'lecturers' => 0,
                'national_accreditation' => '',
                'international_accreditation' => '',
                'approval_sk' => null,
                'opening_year' => null,
                'director_name' => 'Ir. Ahmad Bakri Muhiddin, M.Sc., PhD',
                'director_contact' => '082187423294',
                'ukt_fee' => null,
                'ipi_fee' => null,
                'international_exposure' => null,
                'total_courses' => 0,
                'rps_courses_in_english' => 0,
                'teaching_materials_in_english' => 0,
                'courses_delivered_in_english' => 0,
                'courses_fully_filled_in_sikola' => 0, 
            ],
            [
                'study_program_Name' => 'TEKNIK INFORMATIKA - S1',
                'ID_Faculty' => 4,
                'study_program_Image' => $this->storeImage('infor.png'),
                'study_program_Description' =>'The International Class Program in Computer Engineering is designed to prepare students to become experts in information technology with global standards. This program offers a comprehensive curriculum covering three main concentrations: Artificial Intelligence, Cloud Computing and Big Data, and the Internet of Things. Students have the opportunity to participate in exchange programs and internships at leading technology companies abroad. Through this program, students are expected to compete in the global job market, possess in-depth technical skills, and thrive in multicultural work environments.',
                'degree' => 'Undergraduate',
                'classrooms' => 0,
                'lecturers' => 0,
                'national_accreditation' => 'Unggul',
                'international_accreditation' => 'ASIIN',
                'approval_sk' => null,
                'opening_year' => 2022,
                'director_name' => 'Anugrayani Bustamin, ST., MT',
                'director_contact' => '08114446575',
                'ukt_fee' => 16000000,
                'ipi_fee' => 35000000,
                'international_exposure' => null,
                'total_courses' => 70,
                'rps_courses_in_english' => 40,
                'teaching_materials_in_english' => 31,
                'courses_delivered_in_english' => 31,
                'courses_fully_filled_in_sikola' => 0, 
            ],[
                'study_program_Name' => 'TEKNIK ARSITEKTUR - S1',
                'ID_Faculty' => 4,
                'study_program_Image' => $this->storeImage('arsitektur.png'),
                'study_program_Description' =>'',
                'degree' => 'Undergraduate',
                'classrooms' => 0,
                'lecturers' => 0,
                'national_accreditation' => '',
                'international_accreditation' => '',
                'approval_sk' => null,
                'opening_year' => null,
                'director_name' => 'Dr. Eng. Asniawaty, ST., MT',
                'director_contact' => '081234567896',
                'ukt_fee' => null,
                'ipi_fee' => null,
                'international_exposure' => null,
                'total_courses' => 0,
                'rps_courses_in_english' => 0,
                'teaching_materials_in_english' => 0,
                'courses_delivered_in_english' => 0,
                'courses_fully_filled_in_sikola' => 0, 
            ],
            [
                'study_program_Name' => 'TEKNIK GEOLOGI - S1',
                'ID_Faculty' => 4,
                'study_program_Image' => $this->storeImage('geo.png'),
                'study_program_Description' =>'',
                'degree' => 'Undergraduate',
                'classrooms' => 0,
                'lecturers' => 0,
                'national_accreditation' => '',
                'international_accreditation' => '',
                'approval_sk' => null,
                'opening_year' => null,
                'director_name' => 'Dr. Hendra Fachri',
                'director_contact' => null,
                'ukt_fee' => null,
                'ipi_fee' => null,
                'international_exposure' => null,
                'total_courses' => 0,
                'rps_courses_in_english' => 0,
                'teaching_materials_in_english' => 0,
                'courses_delivered_in_english' => 0,
                'courses_fully_filled_in_sikola' => 0, 
            ],
            [
                'study_program_Name' => 'ILMU HUKUM - S1',
                'ID_Faculty' => 2,
                'study_program_Image' => $this->storeImage('FH-UNHAS-10.png'),
                'study_program_Description' =>'',
                'degree' => 'Undergraduate',
                'classrooms' => 3,
                'lecturers' => 0,
                'national_accreditation' => 'Unggul',
                'international_accreditation' => 'FIBAA',
                'approval_sk' => null,
                'opening_year' => null,
                'director_name' => 'Dr. Muhammad Ilham Arisaputra, S.H., M.Kn',
                'director_contact' => '08114122855',
                'ukt_fee' => 15000000,
                'ipi_fee' => null,
                'international_exposure' => 'Summer School, Short Courses',
                'total_courses' => 0,
                'rps_courses_in_english' => 0,
                'teaching_materials_in_english' => 0,
                'courses_delivered_in_english' => 0,
                'courses_fully_filled_in_sikola' => 0, 
            ],
            [
                'study_program_Name' => 'ILMU HUBUNGAN INTERNASIONAL - S1',
                'ID_Faculty' => 5,
                'study_program_Image' => $this->storeImage('hi.png'),
                'study_program_Description' =>'',
                'degree' => 'Undergraduate',
                'classrooms' => 0,
                'lecturers' => 0,
                'national_accreditation' => '',
                'international_accreditation' => '',
                'approval_sk' => null,
                'opening_year' => null,
                'director_name' => 'Aswin Baharuddin, S.IP.,MA',
                'director_contact' => null,
                'ukt_fee' => null,
                'ipi_fee' => null,
                'international_exposure' => null,
                'total_courses' => 0,
                'rps_courses_in_english' => 0,
                'teaching_materials_in_english' => 0,
                'courses_delivered_in_english' => 0,
                'courses_fully_filled_in_sikola' => 0, 
            ],
            [
                'study_program_Name' => 'ILMU KOMUNIKASI - S1',
                'ID_Faculty' => 5,
                'study_program_Image' => $this->storeImage('ilkom.png'),
                'study_program_Description' =>'',
                'degree' => 'Undergraduate',
                'classrooms' => 0,
                'lecturers' => 0,
                'national_accreditation' => '',
                'international_accreditation' => '',
                'approval_sk' => null,
                'opening_year' => null,
                'director_name' => 'Dr. Sudirman Karnay, M.Si.',
                'director_contact' => null,
                'ukt_fee' => null,
                'ipi_fee' => null,
                'international_exposure' => null,
                'total_courses' => 0,
                'rps_courses_in_english' => 0,
                'teaching_materials_in_english' => 0,
                'courses_delivered_in_english' => 0,
                'courses_fully_filled_in_sikola' => 0, 
            ],
            [
                'study_program_Name' => 'MANAJEMEN - S1',
                'ID_Faculty' => 1,
                'study_program_Image' => $this->storeImage('Fakultas-Ekonomi-dan-Bisnis.png'),
                'study_program_Description' =>'',
                'degree' => 'Undergraduate',
                'classrooms' => 2,
                'lecturers' => 0,
                'national_accreditation' => 'Unggul',
                'international_accreditation' => 'AUN-QA',
                'approval_sk' => null,
                'opening_year' => 2016,
                'director_name' => 'Hermita Arif, S.E., CIFP., M.Com',
                'director_contact' => '085298590726',
                'ukt_fee' => 15000000,
                'ipi_fee' => null,
                'international_exposure' => 'Double Degree, Study Abroad (Credit Transfer), Summer School',
                'total_courses' => 45,
                'rps_courses_in_english' => 0,
                'teaching_materials_in_english' => 0,
                'courses_delivered_in_english' => 0,
                'courses_fully_filled_in_sikola' => 0, 
            ],
            [
                'study_program_Name' => 'AKUTANSI - S1',
                'ID_Faculty' => 1,
                'study_program_Image' => $this->storeImage('Fakultas-Ekonomi-dan-Bisnis.png'),
                'study_program_Description' =>'',
                'degree' => 'Undergraduate',
                'classrooms' => 0,
                'lecturers' => 0,
                'national_accreditation' => '',
                'international_accreditation' => '',
                'approval_sk' => null,
                'opening_year' => null,
                'director_name' => 'Hermita Arif, S.E., CIFP., M.Com',
                'director_contact' => '085298590726',
                'ukt_fee' => null,
                'ipi_fee' => null,
                'international_exposure' => null,
                'total_courses' => 56,
                'rps_courses_in_english' => 6,
                'teaching_materials_in_english' => 0,
                'courses_delivered_in_english' => 0,
                'courses_fully_filled_in_sikola' => 0, 
            ],
            [
                'study_program_Name' => 'SISTEM INFORMASI - S1',
                'ID_Faculty' => 8,
                'study_program_Image' => $this->storeImage('Fakultas-Ekonomi-dan-Bisnis.png'),
                'study_program_Description' =>
                    '(PRODI TESTING) The Information Systems program focuses on integrating business and technology. It provides a strong foundation in systems analysis, database management, and IT governance, preparing students for careers in business technology management.',
                'degree' => 'Undergraduate',
                'classrooms' => 20,
                'lecturers' => 40,
                'national_accreditation' => 'A',
                'international_accreditation' => 'AACSB',
                'approval_sk' => 'SK136',
                'opening_year' => 2010,
                'director_name' => 'Dr. Rika Susanti',
                'director_contact' => '081234567803',
                'ukt_fee' => 11000000,
                'ipi_fee' => 7500000,
                'international_exposure' => 'Industry Collaboration Projects',
                'total_courses' => 0,
                'rps_courses_in_english' => 0,
                'teaching_materials_in_english' => 0,
                'courses_delivered_in_english' => 0,
                'courses_fully_filled_in_sikola' => 0, 
            ],
        ];

        DB::table('study_programs')->insert($programs);
    }
    private function storeImage($fileName)
    {
        $sourcePath = public_path("images/studyprogram/$fileName");
        

        if (file_exists($sourcePath)) {
            Storage::disk('public')->putFileAs('images/studyprogram', $sourcePath, $fileName);

            return 'images/studyprogram/'.$fileName;
        }

        return null; 
    }
}
